<div class="modal hide fade yulong" id="editor" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" mf="modalfix" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"><?php echo Enum_Lang::getPageText('news', 'editTagTitle'); ?></h4>
            </div>
            <div class="modal-body" id="detailBody" mf="modalfix">
                <form class="form-horizontal" id="listEditor">
                    <input type="hidden" id="edit_id" value="0">
                    <?php $filedTitle = Enum_Lang::getPageText('news', 'tagTitle'); ?>
                    <?php foreach ($languageList as $language) { ?>
                        <div class="control-group" op="editFiled">
                            <label class="control-label" for="edit_title"><?php echo $filedTitle; ?>(<?php echo Enum_Lang::getPageText('language', $language); ?>)：</label>
                            <div class="controls">
                                <input type="text" id="edit_titleLang<?php echo Enum_Lang::getLangIndex($language); ?>"
                                       placeholder="<?php echo $filedTitle; ?>" class="span3"
                                       data-title="<?php echo $filedTitle; ?>">
                            </div>
                        </div>
                    <?php } ?>

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" id="saveListData"
                        data-loading-text="<?php echo Enum_Lang::getPageText('system', 'saveing'); ?>"><?php echo Enum_Lang::getPageText('system', 'save'); ?></button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" id='closeEditor'><?php echo Enum_Lang::getPageText('system', 'close'); ?></button>
            </div>
        </div>
    </div>
</div>
