<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title><?php echo Enum_Lang::getPageText('system', 'systemName'); ?></title>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>/css/reset.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>/css/style.css"/>
</head>
<body id="login">
<div id="login-wrapper" class="png_bg">
    <div id="login-top">
        <h1><?php echo Enum_Lang::getPageText('system', 'systemName'); ?></h1>
    </div>
    <!-- End #logn-top -->
    <div id="login-content">
        <form id="loginForm">
            <div class="notification information png_bg">
                <div id="message" style="display: none;"></div>
            </div>
            <p>
                <label><?php echo Enum_Lang::getPageText('login', 'username'); ?>：</label>
                <input class="text-input" type="text" name="userName" id="userName"/>
            </p>
            <div class="clear"></div>
            <p>
                <label><?php echo Enum_Lang::getPageText('login', 'password'); ?>：</label>
                <input class="text-input" type="password" name="userPass" type="password" id="userPass"/>
            </p>
            <div class="clear"></div>
            <p>
                <input class="button" type="button" id="submitForm" value="<?php echo Enum_Lang::getPageText('login', 'loginButton'); ?>"/>
            </p>
        </form>
    </div>
    <!-- End #login-content -->
</div>
<!-- End #login-wrapper -->
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/jquery-1.11.1.min.js"></script>
<?php include($webConfig['layoutPath'] . '/common/record.phtml') ?>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_ajax.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/login/index.js" type="text/javascript"></script>
</body>
</html>
