<meta charset="utf-8">
<title><?php echo Enum_Lang::getPageText('system', 'systemName'); ?></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/bootstrap.css"/>
<link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/al_resize.css"/>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/jquery-1.11.1.min.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_ajax.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_alert.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/modalfix.js" type="text/javascript"></script>
<link href="<?php echo $webConfig['imgDomain']; ?>css/css.css" rel="stylesheet">
