<div class="span2">
    <div class="well side-nav">
        <ul class="nav nav-list" id="navList">
            <li class="nav-header">
                <span class="nav-header-open">
                    <i class="icon-plus icon-plus-opacity pull-right"></i><?php echo Enum_Lang::getPageText('nav', 'groupManager'); ?>
                </span>
                <ul class="nav nav-list nav-li-list hide">
                    <li><a href="/group/userList"><?php echo Enum_Lang::getPageText('nav', 'groupUser'); ?></a></li>
                    <li><a href="/hotel/hotelList"><?php echo Enum_Lang::getPageText('nav', 'hotelList'); ?></a></li>
                    <li><a href="/group/staffList"><?php echo Enum_Lang::getPageText('nav', 'staffList'); ?></a></li>
                </ul>
            </li>
            <li class="nav-header">
                <span class="nav-header-open">
                    <i class="icon-plus icon-plus-opacity pull-right"></i><?php echo Enum_Lang::getPageText('nav', 'activity'); ?>
                </span>
                <ul class="nav nav-list nav-li-list hide">
                    <li><a href="/activity/tag"><?php echo Enum_Lang::getPageText('nav', 'activityTag'); ?></a></li>
                    <li><a href="/activity/list"><?php echo Enum_Lang::getPageText('nav', 'activityList'); ?></a></li>
                    <li><a href="/activity/order"><?php echo Enum_Lang::getPageText('nav', 'activityOrder'); ?></a></li>
                </ul>
            </li>
            <li class="nav-header">
                <span class="nav-header-open">
                    <i class="icon-plus icon-plus-opacity pull-right"></i><?php echo Enum_Lang::getPageText('nav', 'news'); ?>
                </span>
                <ul class="nav nav-list nav-li-list hide">
                    <li><a href="/news/tagList"><?php echo Enum_Lang::getPageText('nav', 'newsTag'); ?></a></li>
                    <li><a href="/news/list"><?php echo Enum_Lang::getPageText('nav', 'newsList'); ?></a></li>
                </ul>
            </li>
            <li class="nav-header">
                <span class="nav-header-open">
                    <i class="icon-plus icon-plus-opacity pull-right"></i><?php echo Enum_Lang::getPageText('nav', 'notic'); ?>
                </span>
                <ul class="nav nav-list nav-li-list hide">
                    <li><a href="/notic/tagList"><?php echo Enum_Lang::getPageText('nav', 'noticTag'); ?></a></li>
                    <li><a href="/notic/list"><?php echo Enum_Lang::getPageText('nav', 'noticList'); ?></a></li>
                </ul>
            </li>
            <li class="nav-header">
                <span class="nav-header-open">
                    <i class="icon-plus icon-plus-opacity pull-right"></i><?php echo Enum_Lang::getPageText('nav', 'appManager'); ?>
                </span>
                <ul class="nav nav-list nav-li-list hide">
                    <li><a href="/app/startMsgList"><?php echo Enum_Lang::getPageText('nav', 'startMsgList'); ?></a></li>
                    <li><a href="/app/groupPush"><?php echo Enum_Lang::getPageText('nav', 'groupPush'); ?></a></li>
                    <li><a href="/app/startPicList"><?php echo Enum_Lang::getPageText('nav', 'startPicList'); ?></a></li>
                    <li><a href="/app/versionList"><?php echo Enum_Lang::getPageText('nav', 'versionList'); ?></a></li>
                    <li><a href="/app/appImgList"><?php echo Enum_Lang::getPageText('nav', 'appImgList'); ?></a></li>
                    <li><a href="/app/feedbackList"><?php echo Enum_Lang::getPageText('nav', 'feedbackList'); ?></a></li>
                    <li><a href="/app/about"><?php echo Enum_Lang::getPageText('nav', 'about'); ?></a></li>
                </ul>
            </li>
            <li class="nav-header">
                <span class="nav-header-open">
                    <i class="icon-plus icon-plus-opacity pull-right"></i><?php echo Enum_Lang::getPageText('nav', 'help'); ?>
                </span>
                <ul class="nav nav-list nav-li-list hide">
                    <li><a href="/help/type"><?php echo Enum_Lang::getPageText('nav', 'helpType'); ?></a></li>
                    <li><a href="/help/list"><?php echo Enum_Lang::getPageText('nav', 'helpList'); ?></a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>
<script type="text/javascript">
    var log = console.log.bind(console) || alert;
    $(function () {
        var pathname = window.location.pathname;
        var defaultSelected = 0;
        if (!pathname) {
            defaultSelected = 1;
        }

        $('.nav-li-list a').each(function (i, item) {
            var item = $(item);
            if (defaultSelected) {
                if (i == 0) {
                    item.parent().addClass('active').parent('ul').removeClass('hide');
                    return;
                }
            } else {
                if (item.attr('href') == pathname) {
                    item.parent().addClass('active').parent('ul').removeClass('hide').prev().children('i').removeClass('icon-plus').addClass('icon-minus');
                    return;
                }
            }
        });

        $('.nav-header-open').on('click', function () {
            var T = $(this);
            var flag = T.next('.nav-li-list').toggle().css('display');
            if (flag == 'block') {
                T.find('i').removeClass('icon-plus').addClass('icon-minus');
                var item = T.parents('ul').siblings().find('.nav-li-list').hide();
            } else {
                T.find('i').removeClass('icon-minus').addClass('icon-plus');
            }
            T.parents('ul').siblings().find('i').removeClass('icon-minus').addClass('icon-plus');
        })
    });
</script>
