<!DOCTYPE HTML>
<html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/select2.min.css"/>
</head>
<body>
<?php include($webConfig['layoutPath'] . '/common/header.phtml') ?>
<div class="container container-main">
    <div class="row-fluid">
        <?php include($webConfig['layoutPath'] . '/common/nav.phtml') ?>
        <div class="span10">
            <div class="cont-mod">
                <div class="page-header page-header-custom">
                    <h1 class="h1-custom">
                        <?php echo Enum_Lang::getPageText('nav', 'helplist'); ?>
                        <button id="createData" class="btn btn-info" style="margin-left: 5px;" type="button" data-toggle="modal" data-target="#editor"><?php echo Enum_Lang::getPageText('system', 'create'); ?>
                        </button>
                    </h1>
                </div>
                <?php include($webConfig['layoutPath'] . '/help/help_filter.phtml') ?>
                <div class="cont-mod">
                    <div class="page-header page-header-custom"></div>
                    <div class="reservation">
                        <div>
                            <div class="res-table sys-table-auto">
                                <table width="100%" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th><?php echo Enum_Lang::getPageText('help', 'type'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('help', 'title'); ?>(<?php echo Enum_Lang::getPageText('language', 'zh'); ?>)</th>
                                        <th><?php echo Enum_Lang::getPageText('help', 'title'); ?>(<?php echo Enum_Lang::getPageText('language', 'en'); ?>)</th>
                                        <th><?php echo Enum_Lang::getPageText('help', 'sort'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('help', 'createTime'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('help', 'status'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('system', 'option'); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="dataList"></tbody>
                                </table>
                            </div>
                            <div id="pageDiv" style='padding: 20px;'></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include($webConfig['layoutPath'] . '/help/help_edit.phtml'); ?>
<script type="text/javascript">
    var YP_GLOBAL_VARS = {
        checkParams: '<?php echo json_encode(Enum_Help::getHelpMustInput());?>',
        listUrl: '/helpajax/getList',
        createUrl: '/helpajax/create',
        updateUrl: '/helpajax/update'
    };
</script>
<?php include($webConfig['layoutPath'] . '/common/list_common.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/common/record.phtml') ?>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_list.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_form.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/art.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/select2.full.min.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/zh-CN.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/help/help.js"></script>
</body>
</html>
<script id="dataList_tpl" type="text/html">
    {{each list as info i}}
    <tr dataId="{{info.id}}">
        <td type="id" data-value="{{info.id}}">{{info.id}}</td>
        <td type="typeid" data-value="{{info.typeid}}">{{info.typeShow}}</td>
        <td type="titleZh" data-value="{{info.titleZh}}">{{info.titleZh}}</td>
        <td type="titleEn" data-value="{{info.titleEn}}">{{info.titleEn}}</td>
        <td type="sort" data-value="{{info.sort}}">{{info.sort}}</td>
        <td>{{info.createtime}}</td>
        <td type="status" data-value="{{info.status}}">{{info.statusShow}}</td>
        <td>
            <button op="editDataOne" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}"><?php echo Enum_Lang::getPageText('system', 'edit'); ?></button>
            <button op="editArticle" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}" data-type="<?php echo Enum_Article::ARTICLE_TYPE_HELP_ZH; ?>" data-article="{{info.helpZh}}"><?php echo Enum_Lang::getPageText('system', 'article'); ?>(<?php echo Enum_Lang::getPageText('language', 'zh'); ?>)</button>
            <button op="editArticle" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}" data-type="<?php echo Enum_Article::ARTICLE_TYPE_HELP_EN; ?>" data-article="{{info.helpEn}}"><?php echo Enum_Lang::getPageText('system', 'article'); ?>(<?php echo Enum_Lang::getPageText('language', 'en'); ?>)</button>
        </td>
    </tr>
    {{/each}}
</script>
