<div class="modal hide fade yulong" id="editor" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" mf="modalfix" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"><?php echo Enum_Lang::getPageText('help', 'editTitle'); ?></h4>
            </div>
            <div class="modal-body" id="detailBody" mf="modalfix">
                <form class="form-horizontal" id="listEditor">
                    <input type="hidden" id="edit_id" value="0">
                    <?php $filed = 'typeid'; ?>
                    <?php $filedTitle = Enum_Lang::getPageText('help', 'type'); ?>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_<?php echo $filed; ?>"><?php echo $filedTitle; ?>：</label>
                        <div class="controls">
                            <select id="edit_<?php echo $filed; ?>" data-title="<?php echo $filedTitle; ?>">
                                <?php foreach ($typeList as $typeOne) { ?>
                                    <option value="<?php echo $typeOne['id']; ?>"><?php if (Enum_Lang::getSystemLang() == Enum_Lang::LANG_KEY_CHINESE) {
                                            echo $typeOne['title_zh'];
                                        } else {
                                            echo $typeOne['title_en'];
                                        } ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <?php $filed = 'titleZh'; ?>
                    <?php $filedTitle = Enum_Lang::getPageText('help', 'title') . '(' . Enum_Lang::getPageText('language', 'zh') . ')'; ?>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_<?php echo $filed; ?>"><?php echo $filedTitle; ?>：</label>
                        <div class="controls">
                            <input type="text" id="edit_<?php echo $filed; ?>" placeholder="<?php echo $filedTitle; ?>" class="span3" data-title="<?php echo $filedTitle; ?>">
                        </div>
                    </div>
                    <?php $filed = 'titleEn'; ?>
                    <?php $filedTitle = Enum_Lang::getPageText('help', 'title') . '(' . Enum_Lang::getPageText('language', 'en') . ')'; ?>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_<?php echo $filed; ?>"><?php echo $filedTitle; ?>：</label>
                        <div class="controls">
                            <input type="text" id="edit_<?php echo $filed; ?>" placeholder="<?php echo $filedTitle; ?>" class="span3" data-title="<?php echo $filedTitle; ?>">
                        </div>
                    </div>
                    <?php $filed = 'sort'; ?>
                    <?php $filedTitle = Enum_Lang::getPageText('help', $filed); ?>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_<?php echo $filed; ?>"><?php echo $filedTitle; ?>：</label>
                        <div class="controls">
                            <input type="number" id="edit_<?php echo $filed; ?>" placeholder="<?php echo $filedTitle; ?>" class="span1" data-title="<?php echo $filedTitle; ?>">
                        </div>
                    </div>
                    <?php $filed = 'status'; ?>
                    <?php $filedTitle = Enum_Lang::getPageText('help', 'status'); ?>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_<?php echo $filed; ?>"><?php echo $filedTitle; ?>：</label>
                        <div class="controls">
                            <select id="edit_<?php echo $filed; ?>" data-title="<?php echo $filedTitle; ?>">
                                <option value="0"><?php echo Enum_Lang::getPageText('help', 'disable'); ?></option>
                                <option value="1"><?php echo Enum_Lang::getPageText('help', 'enable'); ?></option>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" id="saveListData" data-loading-text="<?php echo Enum_Lang::getPageText('system', 'saveing'); ?>"><?php echo Enum_Lang::getPageText('system', 'save'); ?></button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" id='closeEditor'><?php echo Enum_Lang::getPageText('system', 'close'); ?></button>
            </div>
        </div>
    </div>
</div>
