<!DOCTYPE HTML>
<html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/select2.min.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/video.css"/>
</head>
<body>
<?php include($webConfig['layoutPath'] . '/common/header.phtml') ?>
<div class="container container-main">
    <div class="row-fluid">
        <?php include($webConfig['layoutPath'] . '/common/nav.phtml') ?>
        <div class="span10">
            <div class="cont-mod">
                <div class="page-header page-header-custom">
                    <h1 class="h1-custom">
                        <?php echo Enum_Lang::getPageText('nav', 'notic'); ?>
                        <button id="createData" class="btn btn-info" style="margin-left: 5px;" type="button" data-toggle="modal" data-target="#editor"><?php echo Enum_Lang::getPageText('system', 'create'); ?>
                        </button>
                    </h1>
                </div>
                <?php include($webConfig['layoutPath'] . '/notic/notic_filter.phtml') ?>
                <div class="cont-mod">
                    <div class="page-header page-header-custom"></div>
                    <div class="reservation">
                        <div>
                            <div class="res-table sys-table-auto">
                                <table width="100%" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <?php foreach ($languageList as $language) { ?>
                                            <th><?php echo Enum_Lang::getPageText('notic', 'title'); ?>（<?php echo Enum_Lang::getPageText('language', $language); ?>）</th>
                                        <?php } ?>
                                        <th><?php echo Enum_Lang::getPageText('notic', 'tagTitle'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('notic', 'pdf'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('notic', 'video'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('notic', 'pic'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('notic', 'sort'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('notic', 'status'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('notic', 'createtime'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('notic', 'updatetime'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('system', 'option'); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="dataList"></tbody>
                                </table>
                            </div>
                            <div id="pageDiv" style='padding: 20px;'></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include($webConfig['layoutPath'] . '/notic/notic_edit.phtml'); ?>
<script type="text/javascript">
    var YP_GLOBAL_VARS = {
        checkParams: '<?php echo json_encode(Enum_Notic::getNoticMustInput());?>',
        listUrl: '/noticajax/getList',
        createUrl: '/noticajax/create',
        updateUrl: '/noticajax/update',
    };
</script>
<?php include($webConfig['layoutPath'] . '/common/list_common.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/common/record.phtml') ?>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_list.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_form.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/art.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/select2.full.min.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/zh-CN.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/plupload/js/plupload.full.min.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/videoUpload.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/notic/list.js"></script>
</body>
</html>
<script id="dataList_tpl" type="text/html">
    {{each list as info i}}
    <tr dataId="{{info.id}}">
        <td type="id" data-value="{{info.id}}">{{info.id}}</td>
<!--        <td type="title" data-value="{{info.title}}">{{info.title}}</td>-->
        <?php foreach ($languageList as $language) { ?>
            <td type="titleLang<?php echo Enum_Lang::getLangIndex($language); ?>" data-value="{{info.titleLang<?php echo Enum_Lang::getLangIndex($language); ?>}}">{{info.titleLang<?php echo Enum_Lang::getLangIndex($language); ?>}}</td>
        <?php } ?>
        <td type="tagid" data-value="{{info.tagid}}">{{info.tagShow}}</td>
        <td type="pdf" data-value="{{info.pdf}}">
            {{if info.pdf}}
            <a href="{{info.pdf}}" target="_blank">
                <?php echo Enum_Lang::getPageText('system', 'view'); ?>
            </a>
            {{/if}}
        </td>
        <td type="video" data-value="{{info.video}}">
            {{if info.video}}
            <a href="{{info.videoShow}}" target="_blank">
                <?php echo Enum_Lang::getPageText('system', 'view'); ?>
            </a>
            {{/if}}
        </td>
        <td type="pic" data-value="{{info.pic}}">
            {{if info.pic}}
            <a href="{{info.pic}}" target="_blank">
                <img src="{{info.pic}}" style="max-width: 100px;max-height: 100px;"/>
            </a>
            {{/if}}
        </td>
        <td type="sort" data-value="{{info.sort}}">{{info.sort}}</td>
        <td type="status" data-value="{{info.status}}">{{info.statusShow}}</td>
        <?php foreach ($languageList as $language) { ?>
            <td style="display: none" type="linkLang<?php echo Enum_Lang::getLangIndex($language); ?>" data-value="{{info.linkLang<?php echo Enum_Lang::getLangIndex($language); ?>}}">{{info.linkLang<?php echo Enum_Lang::getLangIndex($language); ?>}}</td>
        <?php } ?>
        <td type="createtime" data-value="{{info.createtime}}">{{info.createtime}}</td>
        <td type="updatetime" data-value="{{info.updatetime}}">{{info.updatetime}}</td>
        <td>
            <button op="editDataOne" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}"><?php echo Enum_Lang::getPageText('system', 'edit'); ?></button>
            <?php foreach ($languageList as $language) { ?>
                <button op="editArticle" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}" data-type="<?php echo Enum_Article::ARTICLE_TYPE_NOTIC; ?>_<?php echo Enum_Lang::getLangIndex($language); ?>" data-article="{{info.articleLang<?php echo Enum_Lang::getLangIndex($language); ?>}}"><?php echo Enum_Lang::getPageText('system', 'article'); ?>（<?php echo Enum_Lang::getPageText('language', $language); ?>）</button>
            <?php } ?>
        </td>
    </tr>
    {{/each}}
</script>
