<!DOCTYPE HTML>
<html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
</head>
<body>
<?php include($webConfig['layoutPath'] . '/common/header.phtml') ?>
<div class="container container-main">
    <div class="row-fluid">
        <?php include($webConfig['layoutPath'] . '/common/nav.phtml') ?>
        <div class="span10">
            <div class="cont-mod">
                <div class="page-header page-header-custom">
                    <h1 class="h1-custom">
                        <?php echo Enum_Lang::getPageText('staff', 'staffList'); ?>
                        <button id="createData" class="btn btn-info" style="margin-left: 5px;" type="button"
                                data-toggle="modal" data-target="#editor"><?php echo Enum_Lang::getPageText('system', 'create'); ?>
                        </button>
                    </h1>
                </div>
                <?php include($webConfig['layoutPath'] . '/group/staffList_filter.phtml') ?>
                <div class="cont-mod">
                    <div class="page-header page-header-custom"></div>
                    <div class="reservation">
                        <div>
                            <div class="res-table sys-table-auto">
                                <table width="100%" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th><?php echo Enum_Lang::getPageText('staff', 'staffid'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('staff', 'username'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('staff', 'lastLoginTime'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('staff', 'lastLoginIp'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('staff', 'createTime'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('system', 'option'); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="dataList"></tbody>
                                </table>
                            </div>
                            <div id="pageDiv" style='padding: 20px;'></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include($webConfig['layoutPath'] . '/group/staffList_edit.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/group/staff_permission.phtml'); ?>
<script type="text/javascript">
    var YP_GLOBAL_VARS = {
        checkParams: '<?php echo json_encode(Enum_Group::getGroupUserMustInput());?>',
        listUrl: '/staffajax/getStaffList',
        createBaseUrl: '/staffajax/createStaff',
        updateUrl: '/staffajax/updateStaff',
    };
</script>
<?php include($webConfig['layoutPath'] . '/common/list_common.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/common/record.phtml') ?>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_list.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_form.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/art.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/staff/staffList.js"></script>
</body>
</html>
<script id="dataList_tpl" type="text/html">
    {{each list as info i}}
    <tr dataId="{{info.id}}">
        <td type="id" data-value="{{info.id}}" style="display: none;"></td>
        <td type="staffid" data-value="{{info.staffid}}">{{info.staffid}}</td>
        <td type="username" data-value="{{info.username}}">{{info.username}}</td>
        <td>{{info.lastLoginTime}}</td>
        <td>{{info.lastLoginIp}}</td>
        <td>{{info.createTime}}</td>
        <td type="hotelList" data-value="{{info.hotelList}}" style="display: none;"></td>

        <td>
            <button op="editDataOne" type="button" class="btn btn-info btn-sm"
                    data-dataid="{{info.id}}"><?php echo Enum_Lang::getPageText('system', 'edit'); ?></button>
            <button op="editStaffPermission" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}"><?php echo Enum_Lang::getPageText('staff', 'staffPermission'); ?></button>

        </td>
    </tr>
    {{/each}}
</script>
