<div class="modal hide fade yulong" id="editor" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" mf="modalfix" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"><?php echo Enum_Lang::getPageText('group', 'editTitle'); ?></h4>
            </div>
            <div class="modal-body" id="detailBody" mf="modalfix">
                <form class="form-horizontal" id="listEditor">
                    <input type="hidden" id="edit_id" value="0">
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_username"><?php echo Enum_Lang::getPageText('group', 'username'); ?>：</label>
                        <div class="controls">
                            <input type="text" id="edit_username" placeholder="<?php echo Enum_Lang::getPageText('group', 'username'); ?>" class="span3"
                                   data-title="用户名">
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_realname"><?php echo Enum_Lang::getPageText('group', 'realname'); ?>：</label>
                        <div class="controls">
                            <input type="text" id="edit_realname" placeholder="<?php echo Enum_Lang::getPageText('group', 'realname'); ?>" class="span3"
                                   data-title="真实姓名">
                        </div>
                    </div>
                    <div class="control-group" op="editFiled" id="passwordEdit">
                        <label class="control-label" for="edit_password"><?php echo Enum_Lang::getPageText('group', 'password'); ?>：</label>
                        <div class="controls">
                            <input type="text" id="edit_password" placeholder="<?php echo Enum_Lang::getPageText('group', 'pqsswordTips'); ?>" class="span3"
                                   data-title="密码">
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_remark"><?php echo Enum_Lang::getPageText('group', 'remark'); ?>：</label>
                        <div class="controls">
                            <textarea rows="3" id="edit_remark" class="span8" data-title="备注"></textarea>
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_status"><?php echo Enum_Lang::getPageText('group', 'status'); ?>：</label>
                        <div class="controls">
                            <select id="edit_status" data-title="状态">
                                <option value="0"><?php echo Enum_Lang::getPageText('group', 'disable'); ?></option>
                                <option value="1"><?php echo Enum_Lang::getPageText('group', 'enable'); ?></option>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" id="saveListData"
                        data-loading-text="<?php echo Enum_Lang::getPageText('system', 'saveing'); ?>"><?php echo Enum_Lang::getPageText('system', 'save'); ?></button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" id='closeEditor'><?php echo Enum_Lang::getPageText('system', 'close'); ?></button>
            </div>
        </div>
    </div>
</div>
