<!DOCTYPE HTML>
<html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
</head>
<body>
<?php include($webConfig['layoutPath'] . '/common/header.phtml') ?>
<div class="container container-main">
    <div class="row-fluid">
        <?php include($webConfig['layoutPath'] . '/common/nav.phtml') ?>
        <div class="span10">
            <div class="cont-mod">
                <div class="page-header page-header-custom">
                    <h1 class="h1-custom">
                        <?php echo Enum_Lang::getPageText('nav', 'groupPush'); ?>
                        <button id="createData" class="btn btn-info" style="margin-left: 5px;" type="button"
                                data-toggle="modal" data-target="#editor"><?php echo Enum_Lang::getPageText('system', 'create'); ?>
                        </button>
                    </h1>
                </div>
                <?php include($webConfig['layoutPath'] . '/app/push_filter.phtml') ?>
                <div class="cont-mod">
                    <div class="page-header page-header-custom"></div>
                    <div class="reservation">
                        <div>
                            <div class="res-table sys-table-auto">
                                <table width="100%" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th><?php echo Enum_Lang::getPageText('push', 'title'); ?>（<?php echo Enum_Lang::getPageText('language', 'zh'); ?>）</th>
                                        <th><?php echo Enum_Lang::getPageText('push', 'title'); ?>（<?php echo Enum_Lang::getPageText('language', 'en'); ?>）</th>
                                        <th><?php echo Enum_Lang::getPageText('push', 'redirectUrl'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('push', 'pushResult'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('push', 'createTime'); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="dataList"></tbody>
                                </table>
                            </div>
                            <div id="pageDiv" style='padding: 20px;'></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include($webConfig['layoutPath'] . '/app/push_edit.phtml'); ?>
<script type="text/javascript">
    var YP_GLOBAL_VARS = {
        checkParams: '<?php echo json_encode(Enum_app::getPushMustInput());?>',
        listUrl: '/appajax/getPushList',
        createBaseUrl: '/appajax/createPush',
    };
</script>
<?php include($webConfig['layoutPath'] . '/common/list_common.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/common/record.phtml') ?>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_list.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_form.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/art.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/app/push.js"></script>
</body>
</html>
<script id="dataList_tpl" type="text/html">
    {{each list as info i}}
    <tr dataId="{{info.id}}">
        <td type="id" data-value="{{info.id}}">{{info.id}}</td>
        <td type="cnTitle" data-value="{{info.cn_title}}">{{info.cn_title}}</td>
        <td type="enTitle" data-value="{{info.en_title}}">{{info.en_title}}</td>
        <td type="url" data-value="{{info.url}}">
            {{if info.url}}
            <a href="{{info.url}}" target="_blank">
                {{info.url}}
            </a>
            {{/if}}
        </td>
        <td type="result" data-value="{{info.result}}">{{info.resultShow}}</td>
        <td>{{info.createtime}}</td>
    </tr>
    {{/each}}
</script>
