<div class="modal hide fade yulong" id="editor" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
     mf="modalfix" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"><?php echo Enum_Lang::getPageText('startMsg', 'EDITTITLE'); ?></h4>
            </div>
            <div class="modal-body" id="detailBody" mf="modalfix">
                <form class="form-horizontal" id="listEditor">
                    <input type="hidden" id="edit_id" value="0">
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_pic"><?php echo Enum_Lang::getPageText('startMsg', 'showPic'); ?>：</label>
                        <div class="controls">
                            <img src="" id="edit_pic_show" style="max-height: 80px;"/>
                            <input type="file" id="edit_pic" placeholder="<?php echo Enum_Lang::getPageText('startMsg', 'showPic'); ?>" class="span4" data-title="展示图"
                                   accept="<?php echo implode(",", $allowTypeImage); ?>">
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_url"><?php echo Enum_Lang::getPageText('startMsg', 'redirectLink'); ?>：</label>
                        <div class="controls">
                            <input type="text" id="edit_url" placeholder="<?php echo Enum_Lang::getPageText('startMsg', 'redirectLink'); ?>" class="span8"
                                   data-title="跳转URL">
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_msg"><?php echo Enum_Lang::getPageText('startMsg', 'startMsgValue'); ?>：</label>
                        <div class="controls">
                            <textarea rows="3" id="edit_msg" class="span8" data-title="消息内容"></textarea>
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_status"><?php echo Enum_Lang::getPageText('startMsg', 'status'); ?>：</label>
                        <div class="controls">
                            <select id="edit_status" data-title="状态">
                                <option value="0"><?php echo Enum_Lang::getPageText('startMsg', 'disable'); ?></option>
                                <option value="1"><?php echo Enum_Lang::getPageText('startMsg', 'enable'); ?></option>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" id="saveListData"
                        data-loading-text="<?php echo Enum_Lang::getPageText('system', 'saveing'); ?>"><?php echo Enum_Lang::getPageText('system', 'save'); ?></button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" id='closeEditor'><?php echo Enum_Lang::getPageText('system', 'close'); ?></button>
            </div>
        </div>
    </div>
</div>
