<div class="modal hide fade yulong" id="editor" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
     mf="modalfix" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"><?php echo Enum_Lang::getPageText('hotel', 'editTitle'); ?></h4>
            </div>
            <div class="modal-body" id="detailBody" mf="modalfix">
                <form class="form-horizontal" id="listEditor">
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal" id='closeEditor'><?php echo Enum_Lang::getPageText('system', 'close'); ?></button>
            </div>
        </div>
    </div>
</div>
<script type="text/html" id="hotelEdit_tpl">
    {{each langList as langName index}}
    <div class="control-group" op="editFiled">
        <label class="control-label" for="edit_nameLang1"><?php echo Enum_Lang::getPageText('hotel', 'hotelName'); ?>（{{langName}}）：</label>
        <div class="controls">
            {{if filedKey = "nameLang"+index}}{{/if}}
            <input type="text" id="edit_nameLang1" placeholder="<?php echo Enum_Lang::getPageText('hotel', 'hotelName'); ?>（{{langName}}）" class="span4"
                   value="{{dataList[filedKey]}}" readonly>
        </div>
    </div>
    {{/each}}
    <div class="control-group" op="editFiled">
        <label class="control-label" for="edit_nameLang1"><?php echo Enum_Lang::getPageText('hotel', 'city'); ?>：</label>
        <div class="controls">
            <input type="text" id="edit_nameLang1" placeholder="<?php echo Enum_Lang::getPageText('hotel', 'city'); ?>" class="span4"
                   value="{{dataList.city}}" readonly>
        </div>
    </div>
    <div class="control-group" op="editFiled">
        <label class="control-label" for="edit_propertyinterfid">PropertyInterfID：</label>
        <div class="controls">
            <input type="text" id="edit_propertyinterfid" placeholder="PropertyInterfID" class="span4" value="{{dataList.propertyinterfid}}" readonly>
        </div>
    </div>
    <div class="control-group" op="editFiled">
        <label class="control-label" for="edit_lng"><?php echo Enum_Lang::getPageText('hotel', 'lng'); ?>：</label>
        <div class="controls">
            <input type="text" id="edit_lng" placeholder="<?php echo Enum_Lang::getPageText('hotel', 'lng'); ?>" class="span4" value="{{dataList.lng}}" readonly>
        </div>
    </div>
    <div class="control-group" op="editFiled">
        <label class="control-label" for="edit_lat"><?php echo Enum_Lang::getPageText('hotel', 'lat'); ?>：</label>
        <div class="controls">
            <input type="text" id="edit_lat" placeholder="<?php echo Enum_Lang::getPageText('hotel', 'lat'); ?>" class="span4" value="{{dataList.lat}}" readonly>
        </div>
    </div>
    <div class="control-group" op="editFiled">
        <label class="control-label" for="edit_tel"><?php echo Enum_Lang::getPageText('hotel', 'tel'); ?>：</label>
        <div class="controls">
            <input type="text" id="edit_tel" placeholder="<?php echo Enum_Lang::getPageText('hotel', 'tel'); ?>" class="span4" value="{{dataList.tel}}" readonly>
        </div>
    </div>
    <div class="control-group" op="editFiled">
        <label class="control-label" for="edit_website"><?php echo Enum_Lang::getPageText('hotel', 'website'); ?>：</label>
        <div class="controls">
            <input type="text" id="edit_website" placeholder="" class="span4" value="{{dataList.website}}"
                   readonly>
        </div>
    </div>
    <div class="control-group" op="editFiled">
        <label class="control-label" for="edit_logo"><?php echo Enum_Lang::getPageText('hotel', 'hotelLogo'); ?>：</label>
        <div class="controls">
            <a href="{{dataList.logo}}" target="_blank">
                <img src="{{dataList.logo}}" id="edit_logo_show" style="max-height: 80px;"/>
            </a>
        </div>
    </div>
    <div class="control-group" op="editFiled">
        <label class="control-label" for="edit_indexBackground"><?php echo Enum_Lang::getPageText('hotel', 'appBack'); ?>：</label>
        <div class="controls">
            <a href="{{dataList.indexBackground}}" target="_blank">
                <img src="{{dataList.indexBackground}}" id="edit_logo_show" style="max-height: 80px;"/>
            </a>
        </div>
    </div>
    <div class="control-group" op="editFiled">
        <label class="control-label" for="edit_website"><?php echo Enum_Lang::getPageText('hotel', 'status'); ?>：</label>
        <div class="controls">
            <input type="text" id="edit_website" placeholder="<?php echo Enum_Lang::getPageText('hotel', 'status'); ?>" class="span4" value="{{dataList.status}}"
                   readonly>
        </div>
    </div>
    <div class="control-group" op="editFiled">
        <label class="control-label" for="edit_bookurl"><?php echo Enum_Lang::getPageText('hotel', 'bookurl'); ?>：</label>
        <div class="controls">
            <input type="text" id="edit_bookurl" placeholder="<?php echo Enum_Lang::getPageText('hotel', 'bookurl'); ?>" class="span7" value="{{dataList.bookurl}}"
                   readonly>
        </div>
    </div>
    {{each langList as langName index}}
    <div class="control-group" op="editFiled">
        <label class="control-label" for="edit_voiceLang{{index}}"><?php echo Enum_Lang::getPageText('hotel', 'voice'); ?>（{{langName}}）：</label>
        <div class="controls">
            {{if dataNameKey = "voiceLang"+index }} {{/if}}
            {{if dataList[dataNameKey]}}
            <audio src="{{dataList[dataNameKey]}}" id="edit_voiceLang{{index+1}}_show" controls="controls"></audio>
            <br/>
            {{/if}}
        </div>
    </div>
    {{/each}}
    {{each langList as langName index}}
    <div class="control-group" op="editFiled">
        <label class="control-label" for="edit_addressLang{{index}}"><?php echo Enum_Lang::getPageText('hotel', 'address'); ?>（{{langName}}）：</label>
        <div class="controls">
            {{if filedKey = "addressLang"+index}}{{/if}}
            <input type="text" id="edit_addressLang{{index}}" placeholder="<?php echo Enum_Lang::getPageText('hotel', 'address'); ?>（{{langName}}）" class="span8"
                   value="{{dataList[filedKey]}}" readonly>
        </div>
    </div>
    {{/each}}
    {{each langList as langName index}}
    <div class="control-group" op="editFiled">
        <label class="control-label" for="edit_introductionLang{{index}}"><?php echo Enum_Lang::getPageText('hotel', 'introduction'); ?>（{{langName}}）：</label>
        <div class="controls">
            {{if dataNameKey = "introductionLang"+index }} {{/if}}
            <textarea rows="3" id="edit_introductionLang{{index}}" class="span8" data-title="<?php echo Enum_Lang::getPageText('hotel', 'introduction'); ?>（{{langName}}）"
                      readonly>{{dataList[dataNameKey]}}</textarea>
        </div>
    </div>
    {{/each}}
</script>