<!DOCTYPE HTML>
<html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/select2.min.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/jquery-ui-1.8.22.css"/>
</head>
<body>
<?php include($webConfig['layoutPath'] . '/common/header.phtml') ?>
<div class="container container-main">
    <div class="row-fluid">
        <?php include($webConfig['layoutPath'] . '/common/nav.phtml') ?>
        <div class="span10">
            <div class="cont-mod">
                <div class="page-header page-header-custom">
                    <h1 class="h1-custom">
                        物业列表
                        <button id="createData" class="btn btn-info" style="margin-left: 5px;" type="button"
                                data-toggle="modal" data-target="#editor">新建
                        </button>
                    </h1>
                </div>
                <?php include($webConfig['layoutPath'] . '/hotel/hotelList_filter.phtml') ?>
                <div class="cont-mod">
                    <div class="page-header page-header-custom"></div>
                    <div class="reservation">
                        <div>
                            <div class="res-table sys-table-auto">
                                <table width="100%" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>集团</th>
                                        <th>名称</th>
                                        <th>城市</th>
                                        <th>语言</th>
                                        <th>状态</th>
                                        <th>操作</th>
                                    </tr>
                                    </thead>
                                    <tbody id="dataList"></tbody>
                                </table>
                            </div>
                            <div id="pageDiv" style='padding: 20px;'></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include($webConfig['layoutPath'] . '/hotel/hotelList_edit.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/hotel/hotelList_edit_language.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/hotel/hotelList_edit_mutilContent.phtml'); ?>
<script type="text/javascript">
    var YP_GLOBAL_VARS = {
        checkParams: '<?php echo json_encode(Enum_Hotel::getHotelMustInput());?>',
        listUrl: '/hotelajax/getHotelList',
        createBaseUrl: '/hotelajax/createHotel',
        updateBaseUrl: '/hotelajax/updateHotel',
        languageList: '(<?php echo json_encode($languageList);?>)'
    };
</script>

<?php include($webConfig['layoutPath'] . '/common/list_common.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/common/record.phtml') ?>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_list.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_form.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/jquery-ui.min.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/art.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/select2.full.min.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/zh-CN.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/hotel/hotelList.js"></script>
</body>
</html>
<script id="dataList_tpl" type="text/html">
    {{each list as info i}}
    <tr dataId="{{info.id}}">
        <td type="id" data-value="{{info.id}}">{{info.id}}</td>
        <td type="groupid" data-value="{{info.groupid}}">{{info.groupName}}</td>
        <td type="propertyinterfid" data-value="{{info.propertyinterfid}}" style="display:none;"></td>
        <td type="lng" data-value="{{info.lng}}" style="display:none;"></td>
        <td type="lat" data-value="{{info.lat}}" style="display:none;"></td>
        <td type="nameLang1" data-value="{{info.name_lang1}}">{{info.name_lang1}}</td>
        <td type="nameLang2" data-value="{{info.name_lang2}}" style="display:none;"></td>
        <td type="nameLang3" data-value="{{info.name_lang3}}" style="display:none;"></td>
        <td type="cityid" data-value="{{info.cityid}}">{{info.cityName}}</td>
        <td type="tel" data-value="{{info.tel}}" style="display:none;"></td>
        <td type="website" data-value="{{info.website}}" style="display:none;"></td>
        <td type="logo" data-value="{{info.logo}}" style="display:none;"></td>
        <td type="indexBackground" data-value="{{info.index_background}}" style="display:none;"></td>
        <td type="voiceLang1" data-value="{{info.voice_lang1}}" style="display:none;"></td>
        <td type="voiceLang2" data-value="{{info.voice_lang2}}" style="display:none;"></td>
        <td type="voiceLang3" data-value="{{info.voice_lang3}}" style="display:none;"></td>
        <td type="addressLang1" data-value="{{info.address_lang1}}" style="display:none;"></td>
        <td type="addressLang2" data-value="{{info.address_lang2}}" style="display:none;"></td>
        <td type="addressLang3" data-value="{{info.address_lang3}}" style="display:none;"></td>
        <td type="introductionLang1" data-value="{{info.introduction_lang1}}" style="display:none;"></td>
        <td type="introductionLang2" data-value="{{info.introduction_lang2}}" style="display:none;"></td>
        <td type="introductionLang3" data-value="{{info.introduction_lang3}}" style="display:none;"></td>
        <td type="bookurl" data-value="{{info.bookurl}}" style="display:none;"></td>
        <td type="langlist" data-value="{{info.langlist}}">{{info.langListShow}}</td>
        <td type="status" data-value="{{info.status}}">{{info.statusShow}}</td>
        <td>
            <button op="editDataOne" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}">修改</button>
            <button op="editLanguage" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}">语言设置</button>
            {{if info.langlist}}
            <button op="editMutilContent" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}">多语言信息</button>
            {{/if}}
        </td>
    </tr>
    {{/each}}
</script>
