<!DOCTYPE HTML>
<html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/bootstrap-datetimepicker.min.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/select2.min.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/video.css"/>
</head>
<body>
<?php include($webConfig['layoutPath'] . '/common/header.phtml') ?>
<div class="container container-main">
    <div class="row-fluid">
        <?php include($webConfig['layoutPath'] . '/common/nav.phtml') ?>
        <div class="span10">
            <div class="cont-mod">
                <div class="page-header page-header-custom">
                    <h1 class="h1-custom">
                        <?php echo Enum_Lang::getPageText('nav', 'activityList'); ?>
                        <button id="createData" class="btn btn-info" style="margin-left: 5px;" type="button"
                                data-toggle="modal" data-target="#editor"><?php echo Enum_Lang::getPageText('system', 'create'); ?>
                        </button>
                    </h1>
                </div>
                <?php include($webConfig['layoutPath'] . '/activity/activity_filter.phtml') ?>
                <div class="cont-mod">
                    <div class="page-header page-header-custom"></div>
                    <div class="reservation">
                        <div>
                            <div class="res-table sys-table-auto">
                                <table width="100%" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th><?php echo Enum_Lang::getPageText('activity', 'activityTitle'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('activity', 'tagTitle'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('activity', 'pdf'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('activity', 'video'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('activity', 'pic'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('activity', 'sort'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('activity', 'status'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('activity', 'updatetime'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('system', 'option'); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="dataList"></tbody>
                                </table>
                            </div>
                            <div id="pageDiv" style='padding: 20px;'></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include($webConfig['layoutPath'] . '/activity/activity_edit.phtml'); ?>
<script type="text/javascript">
    var YP_GLOBAL_VARS = {
        checkParams: '<?php echo json_encode(Enum_Activity::getActivityMustInput());?>',
        listUrl: '/activityajax/getActivityList',
        createUrl: '/activityajax/createActivity',
        updateUrl: '/activityajax/updateActivity',
    };
</script>
<?php include($webConfig['layoutPath'] . '/common/list_common.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/common/record.phtml') ?>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_list.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_form.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/art.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/select2.full.min.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/zh-CN.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/bootstrap-datetimepicker.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/bootstrap-datetimepicker.zh-CN.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/datatimepicker.config.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/plupload/js/plupload.full.min.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/videoUpload.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/activity/activityList.js"></script>
</body>
</html>
<script id="dataList_tpl" type="text/html">
    {{each list as info i}}
    <tr dataId="{{info.id}}">
        <td type="id" data-value="{{info.id}}">{{info.id}}</td>
        <td type="title" data-value="{{info.title}}">{{info.title}}</td>
        <td type="tagid" data-value="{{info.tagid}}">{{info.tagShow}}</td>
        <td type="pdf" data-value="{{info.pdf}}">
            {{if info.pdf}}
            <a href="{{info.pdf}}" target="_blank">
                <?php echo Enum_Lang::getPageText('system', 'view'); ?>
            </a>
            {{/if}}
        </td>
        <td type="video" data-value="{{info.video}}">
            {{if info.video}}
            <a href="{{info.videoShow}}" target="_blank">
                <?php echo Enum_Lang::getPageText('system', 'view'); ?>
            </a>
            {{/if}}
        </td>
        <td type="pic" data-value="{{info.pic}}">
            {{if info.pic}}
            <a href="{{info.pic}}" target="_blank">
                <img src="{{info.pic}}" style="max-width: 100px;max-height: 100px;"/>
            </a>
            {{/if}}
        </td>
        <td type="sort" data-value="{{info.sort}}">{{info.sort}}</td>
        <td type="status" data-value="{{info.status}}">{{info.statusShow}}</td>
        <td type="createtime" data-value="{{info.createtime}}">{{info.createtime}}</td>
        <td type="fromdate" data-value="{{info.fromdate}}" style="display:none;"></td>
        <td type="todate" data-value="{{info.todate}}" style="display:none;"></td>
        <td type="ordercount" data-value="{{info.ordercount}}" style="display:none;"></td>
        <td>
            <button op="editDataOne" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}"><?php echo Enum_Lang::getPageText('system', 'edit'); ?></button>
            <button op="editArticle" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}" data-type="<?php echo Enum_Article::ARTICLE_TYPE_ACTIVITY; ?>" data-article="{{info.article}}"><?php echo Enum_Lang::getPageText('system', 'article'); ?></button>
        </td>
    </tr>
    {{/each}}
</script>
