<!DOCTYPE HTML>
<html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/select2.min.css"/>
</head>
<body>
<?php include($webConfig['layoutPath'] . '/common/header.phtml') ?>
<div class="container container-main">
    <div class="row-fluid">
        <?php include($webConfig['layoutPath'] . '/common/nav.phtml') ?>
        <div class="span10">
            <div class="cont-mod">
                <div class="page-header page-header-custom">
                    <h1 class="h1-custom">
                        <?php echo Enum_Lang::getPageText('nav', 'activityOrder'); ?>
                    </h1>
                </div>
                <?php include($webConfig['layoutPath'] . '/activity/order_filter.phtml') ?>
                <div class="cont-mod">
                    <div class="page-header page-header-custom"></div>
                    <div class="reservation">
                        <div>
                            <div class="res-table sys-table-auto">
                                <table width="100%" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th><?php echo Enum_Lang::getPageText('activity', 'acitvityOrderName'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('activity', 'acitvityOrderPhone'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('activity', 'ACITVITYORDERORDERCOUNT'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('activity', 'ACITVITYORDERREMARK'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('activity', 'createTime'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('activity', 'activity'); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="dataList"></tbody>
                                </table>
                            </div>
                            <div id="pageDiv" style='padding: 20px;'></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var YP_GLOBAL_VARS = {
        listUrl: '/activityajax/getOrderList'
    };
</script>

<?php include($webConfig['layoutPath'] . '/common/list_common.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/common/record.phtml') ?>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_list.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_form.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/art.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/select2.full.min.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/zh-CN.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/activity/order.js"></script>
</body>
</html>
<script id="dataList_tpl" type="text/html">
    {{each list as info i}}
    <tr dataId="{{info.id}}">
        <td type="id" data-value="{{info.id}}">{{info.id}}</td>
        <td type="name" data-value="{{info.name}}">{{info.name}}</td>
        <td type="phone" data-value="{{info.phone}}">{{info.phone}}</td>
        <td type="ordercount" data-value="{{info.ordercount}}">{{info.ordercount}}</td>
        <td type="remark" data-value="{{info.remark}}">{{info.remark}}</td>
        <td type="createtime" data-value="{{info.createtime}}">{{info.createtime}}</td>
        <td type="activityid" data-value="{{info.activityid}}">{{info.activityName}}</td>
    </tr>
    {{/each}}
</script>
